notifications:
  email:
    recipients:
      - msanchez.jose.94@gmail.com

language: java

script:
        - cd backend/
        - mvn test

after_success:
  - bash <(curl -s https://codecov.io/bash)

